### ISSUE TITLE
Consequent coverage reports *overwrite* each other

### ISSUE THREAD

**Issue by szepeviktor** [timber/timber#2288]
From #2286 

```yaml
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0 IMG_LIBS=1 COVERAGE=1
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=1 IMG_LIBS=0 COVERAGE=1
```

Currently we upload coverage data to Coveralls then we **overwrite** it with multisite coverage data.

What to do now??

**Comment by szepeviktor** [comment]
Maybe https://docs.coveralls.io/parallel-build-webhook?

```yaml
env:
  - COVERALLS_PARALLEL=true

notifications:
  webhooks:
    - https://coveralls.io/webhook
```
